# Defines the A/B update partition scheme
BOOT_A_PARTUUID = "d7804755-193a-47ef-8fa6-966d45aab7a2"
BOOT_A_PROFILE = "boot-profile-a"
BOOT_B_PARTUUID = "52c9b548-2548-4b57-b8df-8193e50e9b45"
BOOT_B_PROFILE = "boot-profile-b"
ROOTFS_A_NAME = "rootfs_a"
ROOTFS_A_PARTUUID = "020977a6-f364-4499-a61c-bc4708908265"
ROOTFS_B_NAME = "rootfs_b"
ROOTFS_B_PARTUUID = "99979fdc-3a79-452d-a62a-cf09030f241b"